let UserType = {
  SET_USER:"SET_USER",
  SET_STEPS:"SET_STEPS",
  SET_COINS_LOGS:"SET_COINS_LOGS",
  SET_TODAY_COINS:"SET_TODAY_COINS",
  SET_COINS:"SET_COINS",
  SET_POSTS:"SET_POSTS",
  SET_COUNTS:"SET_COUNTS",
  SET_SOCIAL_TASKS:"SET_SOCIAL_TASKS",
  SET_ORDERS:"SET_ORDERS",
  SET_ORDER:"SET_ORDER"
 
};

export default UserType;
