let PrizesType = {
    SET_PRIZE_CATEGORIES:"SET_PRIZE_CATEGORIES",
    SET_SELECTED_CATEGORY:"SET_SELECTED_CATEGORY",
    SET_SELECTED_SUB_CATEGORY:"SET_SELECTED_SUB_CATEGORY"
};

export default PrizesType;